const express = require("express")
const cors = require("cors")
const sequelize = require("./database")
require("./models/Libro")
require("./models/Socio")
require("./models/Prestamo")
const librosRoutes = require("./routes/libros")
const sociosRoutes = require("./routes/socios")
9
const prestamosRoutes = require("./routes/prestamos")
const app = express()
app.use(cors())
app.use(express.json())
app.use("/libros", librosRoutes)
app.use("/socios", sociosRoutes)
app.use("/prestamos", prestamosRoutes)
sequelize.sync().then(() => {
console.log("Base de datos conectada")
})
app.listen(3000, () => {
console.log("Servidor corriendo en puerto 3000")
})
