CREATE TABLE Libros (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    stock INTEGER DEFAULT 0,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL
);

CREATE TABLE Socios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre VARCHAR(255) NOT NULL,
    bloqueado BOOLEAN DEFAULT 0,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL
);

CREATE TABLE Prestamos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fechaPrestamo DATETIME,
    fechaDevolucion DATETIME,
    activo BOOLEAN DEFAULT 1,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    
    SocioId INTEGER,
    LibroId INTEGER,

    FOREIGN KEY (SocioId) REFERENCES Socios(id),
    FOREIGN KEY (LibroId) REFERENCES Libros(id)
);